### ISSUE TITLE
Linux: protonvpn doesn't start anymore after python update

### ISSUE THREAD

**Issue by kpspu** [ProtonVPN/linux-app#108]
Clean build of all protonvpn packages doesn't help.
Linux EndeavourOS (Arch). Protonvpn metapackage with all dependencies installed.
Still experiencing this error:

```
$ protonvpn
Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-gui==1.12.0', 'console_scripts', 'protonvpn')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/protonvpn", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/protonvpn_gui/main.py", line 14, in <module>
    from proton.constants import VERSION as proton_version
ModuleNotFoundError: No module named 'proton'
```

**Comment by GarlandKey** [comment]
This fixed the problem for me
```bash
yay -S --rebuild protonvpn-cli protonvpn-gui python-proton-client python-protonvpn-nm-lib
```

**Comment by nautek57** [comment]
I had the same (or similar) issue. I am on ArchLinux, did a system update  (pacman -Syu) and protonvpn is not working anymore.

Just removing the packages and reinstalling them or rebuilding them via paru -S --rebuild protonvpn-cli protonvpn-gui python-proton-client python-protonvpn-nm-lib did not work. I also tried other AUR user suggestions like removing pycache files or removing the protonvpn cache and config cache. Nothing worked. I also ran pacman -Scc to clear all the pacman cache but again it didn't work.

What _finally_ helped was **paru -Scc** which also cleans the AUR caches. Then I rebuilt the protonvpn packages and then it worked. Perhaps that was GarlandKeys note to do a clean build :)

**Comment by scandinave** [comment]
Same error here on Archlinux. I fix it by 

Uninstalling protonvpn 
```
pamac remove protonvpn-cli protonvpn-gui python-protonvpn-nm-lib protonvpn python-proton-client
```

clearing the Aur cache with : 
```
pamac clear --keep 0
```
then reinstalling protonvpn 

```
pamac build protonvpn-cli protonvpn-gui python-protonvpn-nm-lib protonvpn python-proton-client
```

**Comment by codymj** [comment]
I am on Fedora 37 and getting this when trying to run protonvpn:
`
Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-gui==1.12.0', 'console_scripts', 'protonvpn')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/protonvpn", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^
StopIteration
`
I have uninstalled and reinstalled as well as removed any conflicting packages in pip, but issue persists.
