### ISSUE TITLE
App no longer opens on arch linux after an update

### ISSUE THREAD

**Issue by davigamer987** [ProtonVPN/linux-app#112]
❯ protonvpn
Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-gui==1.12.0', 'console_scripts', 'protonvpn')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/protonvpn", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/protonvpn_gui/main.py", line 14, in <module>
    from proton.constants import VERSION as proton_version
  File "/usr/lib/python3.11/site-packages/proton/__init__.py", line 1, in <module>
    from .api import Session # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/proton/api.py", line 21, in <module>
    from .cert_pinning import TLSPinningAdapter
  File "/usr/lib/python3.11/site-packages/proton/cert_pinning.py", line 5, in <module>
    from OpenSSL import crypto
  File "/usr/lib/python3.11/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/lib/python3.11/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/usr/lib/python3.11/site-packages/OpenSSL/crypto.py", line 3263, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'

**Comment by davigamer987** [comment]
I tried rebuilding the packages using yay -S --rebuild protonvpn-cli protonvpn-gui python-proton-client python-protonvpn-nm-lib

That didn't help
