### ISSUE TITLE
Unable to connect wIth ks --on (Manjaro)

### ISSUE THREAD

**Issue by petrpajdla** [ProtonVPN/linux-app#27]
I have an issue with connecting after enabling kill switch (with kill switch off everything works just fine) on Manjaro.

This seems to be related with #12 ?

ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/monitor_vpn_connection_start.py", line 58, in on_vpn_state_changed
    env.killswitch.manage(KillSwitchActionEnum.SOFT)
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/killswitch/killswitch.py", line 82, in manage
    actions_dict = {
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/killswitch/killswitch.py", line 280, in setup_soft_connection
    self.setup_post_connection_ks(None, activating_soft_connection=True)
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/killswitch/killswitch.py", line 221, in setup_post_connection_ks
    self.activate_connection(self.ks_conn_name)
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/killswitch/killswitch.py", line 404, in activate_connection
    conn_dict = self.nm_wrapper.search_for_connection( # noqa
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/dbus/dbus_network_manager_wrapper.py", line 56, in search_for_connection
    all_connection_properties = self.get_settings_from_connection(
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/dbus/dbus_network_manager_wrapper.py", line 418, in get_settings_from_connection
    return iface.GetSettings()
  File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.NetworkManager.Settings.PermissionDenied: uid 1000 has no permission to perform this operation

**Comment by calexandru2018** [comment]
Can you try the provided solution ?

**Comment by petrpajdla** [comment]
I followed the instructions in [https://github.com/ProtonVPN/linux-app/issues/12#issuecomment-876213262](https://github.com/ProtonVPN/linux-app/issues/12#issuecomment-876213262) if this is what you mean, but it did not solve the hang after kill switch is enabled.

The problem is both in the CLI and GUI...

**Comment by calexandru2018** [comment]
So this only happens when you have the KS enabled ?

**Comment by petrpajdla** [comment]
Yes, only with kill switch enabled, both in GUI app (hangs) and CLI (returns an error message copied in the first post).

**Comment by foxfriday** [comment]
you may need to allow notifications from nm-applet. See my comment on #12

**Comment by Excal-rs** [comment]
where u able to fix the killswitch hang?

**Comment by petrpajdla** [comment]
Did a fresh reinstall de to #62, this issue still persists.

@foxfriday nm-applet is run without any flags, so with notifications enabled if I understand it correctly.

**Comment by loufee** [comment]
I too am having this issue after the latest manjaro update.

**Comment by calexandru2018** [comment]
Hey all, I'm happy to announce that this issue has been fixed with the [latest release of the library](https://github.com/ProtonVPN/protonvpn-nm-lib/releases/tag/3.9.0). Please update to the latest version.
