### ISSUE TITLE
Error loading servers errno 5

### ISSUE THREAD

**Issue by kumikooumae** [ProtonVPN/linux-app#54]
A popup shows up when starting the app, saying Error loading servers [Errno 5] 输入/输出错误. 

-------------------------------------------------

-----------	Initialized protonvpn	-----------

-------------------------------------------------
2021-11-02 17:14:16,898 — main.py — INFO —do_startup:87 — ProtonVPN v1.5.1 (protonvpn-nm-lib v3.6.0; proton-client v0.7.1)
2021-11-02 17:14:16,923 — main.py — INFO —do_startup:109 — Startup successful
2021-11-02 17:14:17,025 — dashboard.py — INFO —setup_icons_images:378 — Setting up dashboard images and icons
2021-11-02 17:14:17,030 — dashboard.py — INFO —setup_css:450 — Setting up css
2021-11-02 17:14:17,032 — dashboard.py — INFO —setup_actions:477 — Setting up actions
2021-11-02 17:14:17,037 — main.py — INFO —do_activate:266 — Window to display <dashboard.DashboardView object at 0x7f786bb0f300 (DashboardView at 0x55ec9e1d42c0)>
2021-11-02 17:14:18,641 — dashboard.py — ERROR —__on_startup:175 — [Errno 5] 输入/输出错误
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/protonvpn_gui/view_model/dashboard.py", line 173, in __on_startup
    self.__server_list_vm.on_load_servers()
  File "/usr/lib/python3.9/site-packages/protonvpn_gui/view_model/server_list.py", line 40, in on_load_servers
    self.__generate_server_list()
  File "/usr/lib/python3.9/site-packages/protonvpn_gui/view_model/server_list.py", line 48, in __generate_server_list
    self.server_list_model.generate_list(
  File "/usr/lib/python3.9/site-packages/protonvpn_gui/model/server_list.py", line 65, in generate_list
    res = exec.map(self._generate_process, _jobs)
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 726, in map
    results = super().map(partial(_process_chunk, fn),
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 597, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 597, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 697, in submit
    self._adjust_process_count()
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 675, in _adjust_process_count
    p.start()
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.9/multiprocessing/popen_fork.py", line 16, in __init__
    util._flush_std_streams()
  File "/usr/lib64/python3.9/multiprocessing/util.py", line 439, in _flush_std_streams
    sys.stderr.flush()
OSError: [Errno 5] 输入/输出错误

**Comment by parrotx-proton** [comment]
Duplicate of #35 
Workaround: https://github.com/ProtonVPN/linux-app/issues/35#issuecomment-964668538
