### ISSUE TITLE
Unable to Launch Session

### ISSUE THREAD

**Issue by CPete88** [ProtonVPN/linux-app#58]
I am not able to launch the Linux CLI or App. I get the following error when I try to run `protonvpn` or  `protonvpn-cli login <username>`. Since I use SUSE 15.3, I build this App tool along with the `protonvpn-nm-lib` and the `protonvpn-cli` package on my machine.

Versions I built:
protonvpn-nm-lib version I built: 3.6.1
protonvpn-cli version I built: 3.10.1
protonvpn-gui version I built: 1.6.0

`protonvpn-cli login <username>` output:
```
Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 11, in <module>
    load_entry_point('protonvpn-cli==3.10.1', 'console_scripts', 'protonvpn-cli')()
  File "/usr/lib/python3.6/site-packages/protonvpn_cli-3.10.1-py3.6.egg/protonvpn_cli/main.py", line 21, in main
  File "/usr/lib/python3.6/site-packages/protonvpn_cli-3.10.1-py3.6.egg/protonvpn_cli/cli.py", line 65, in __init__
  File "/usr/lib/python3.6/site-packages/protonvpn_cli-3.10.1-py3.6.egg/protonvpn_cli/cli.py", line 162, in login
  File "/usr/lib/python3.6/site-packages/protonvpn_cli-3.10.1-py3.6.egg/protonvpn_cli/cli_wrapper.py", line 63, in login
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/api.py", line 322, in check_session_exists
    return self._env.api_session.is_valid
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/core/environment.py", line 54, in api_session
    self.__api_session = APISession()
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/core/session/session.py", line 206, in __init__
    self.__session_create()
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/core/session/session.py", line 233, in __session_create
    tls_pinning=self._enforce_pinning,
TypeError: __init__() got an unexpected keyword argument 'log_dir_path'
```
`protonvpn` output:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/protonvpn_gui-1.6.0-py3.6.egg/protonvpn_gui/main.py", line 261, in do_activate
    if not protonvpn.check_session_exists():
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/api.py", line 322, in check_session_exists
    return self._env.api_session.is_valid
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/core/environment.py", line 54, in api_session
    self.__api_session = APISession()
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/core/session/session.py", line 206, in __init__
    self.__session_create()
  File "/usr/lib/python3.6/site-packages/protonvpn_nm_lib-3.6.1-py3.6.egg/protonvpn_nm_lib/core/session/session.py", line 233, in __session_create
    tls_pinning=self._enforce_pinning,
TypeError: __init__() got an unexpected keyword argument 'log_dir_path'
```

**Comment by calexandru2018** [comment]
Hey @CPete88 

You’re not using the latest version of the proton-client (https://github.com/ProtonMail/proton-python-client)

**Comment by CPete88** [comment]
@calexandru2018 Thank you for information. I did not realize that I needed a 3rd dependency. Let me try building and installing this client.

**Comment by calexandru2018** [comment]
It’s not actually a 3rd party, as it’s also maintained by me but it’s in the core two account.

**Comment by CPete88** [comment]
@calexandru2018 My appologies. I meant that I was assuming I only needed packages "protonvpn-nm-lib" and "protonvpn-cli".

Good news. I can now launch the Linux CLI and log into ProtonVPN.

The next step is getting the GUI App to launch. I built and installed the GUI again. But when I try to find a command or a GNOME app launcher to start the GUI, I find nothing. Is there an additional step that is required to be able to start the GUI?

**Comment by CPete88** [comment]
Current packages installed on my SUSE 15.3 machine.

directory: /usr/lib/python3.6/site-packages/

- protonvpn_cli
- protonvpn_cli-2.2.11.dist-info
- protonvpn_cli-3.10.1-py3.6.egg
- protonvpn_gui-1.6.0-py3.6.egg
- protonvpn_nm_lib-3.6.1-py3.6.egg-

**Comment by CPete88** [comment]
For now, I was able to extract the icon.png and .desktop file from the Fedora 33 RPM file. Moving these files to the corresponding location on my machine allows me to start the GUI.

Not sure if this GUI package is supposed to install the icon.png and .desktop files?
