### ISSUE TITLE
Did the last update break the app for some Linux users or distributions?

### ISSUE THREAD

**Issue by renatoliveira** [ProtonVPN/linux-app#61]
For example, when I try to open the ProtonVPN app through the icon on the Gnome bar, nothing happens. When I try to run `protonvpn` on the command line, I get a Python missing import error.

Like this:

```
➜  ~ protonvpn
Traceback (most recent call last):
  File "/sbin/protonvpn", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-gui==1.7.0', 'console_scripts', 'protonvpn')())
  File "/sbin/protonvpn", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/protonvpn_gui/main.py", line 14, in <module>
    from proton.constants import VERSION as proton_version
ModuleNotFoundError: No module named 'proton'
```

**Comment by W-Hamra** [comment]
Yes. I had the same issue. The problem for me was the python update from 3.9 to 3.10. The proton module remained in 3.9, and it's handled by python-proton-client on ArchLinux. If you're on arch, rebuild this package. If you're on some other distro, check who owns "/usr/lib/pythonXXX/site_packages/proton", and rebuild that package.

**Comment by calexandru2018** [comment]
Hey @renatoliveira 

Yes it is indeed as @W-Hamra explained it. It has to do with the python upgrade.

**Comment by renatoliveira** [comment]
That's wonderful. Thank you both.

**Comment by calexandru2018** [comment]
You’ll have to do that for all deps. Maybe easier to just re-install it.

**Comment by renatoliveira** [comment]
Yep. That did it.

For anyone wondering, if you had the same issue I did, you might have the same `ModuleNotFoundError` that I happened to have. If that's the case, check if you have the ProtonVPN NetworkManager Library installed too.

On Arch you can install it from the official packages, its the `python-protonvpn-nm-lib` one.
