### ISSUE TITLE
unable to run protonvpn

### ISSUE THREAD

**Issue by Excal-rs** [ProtonVPN/linux-app#62]
I am not able to launch the Linux CLI or App. I get the following error when I try to run  protonvpn-gui and protonvpn-cli:
`Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/protonvpn_gui/main.py", line 262, in do_activate
    if not protonvpn.check_session_exists():
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/api.py", line 344, in check_session_exists
    return self._env.api_session.is_valid
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/environment.py", line 55, in api_session
    self.__api_session = APISession()
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/session/session.py", line 211, in __init__
    self.__session_create()
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/session/session.py", line 232, in __session_create
    self.__proton_api = Session(
TypeError: __init__() got an unexpected keyword argument 'log_dir_path'
`

**Comment by Graninius** [comment]
All the same. Manjaro KDE, unstabile. It doesn't start.

**Comment by Excal-rs** [comment]
> All the same. Manjaro KDE, unstabile. It doesn't start.
> 
> `❯ protonvpn
> Traceback (most recent call last):
>   File "/usr/bin/protonvpn", line 33, in <module>
>     sys.exit(load_entry_point('protonvpn-gui==1.7.0', 'console_scripts', 'protonvpn')())
>   File "/usr/bin/protonvpn", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
>     module = import_module(match.group('module'))
>   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/usr/lib/python3.10/site-packages/protonvpn_gui/main.py", line 14, in <module>
>     from proton.constants import VERSION as proton_version
> ModuleNotFoundError: No module named 'proton'
> 
> 
> ❯ protonvpn-cli
> Traceback (most recent call last):
>   File "/usr/bin/protonvpn-cli", line 33, in <module>
>     sys.exit(load_entry_point('protonvpn-cli==3.11.0', 'console_scripts', 'protonvpn-cli')())
>   File "/usr/lib/python3.10/site-packages/protonvpn_cli/main.py", line 20, in main
>     from .cli import ProtonVPNCLI
>   File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 4, in <module>
>     from proton.constants import VERSION as proton_version
> ModuleNotFoundError: No module named 'proton'
> `

yeah it might be something wrong with manjaro, I might try downgrading protonvpn and all dependicies. (also u formatted the code incorrectly use three ` instead of just one)
```
like this
```

**Comment by calexandru2018** [comment]
Hey all,

this issue might be due to the python upgrade. Try uninstall first all packages, make sure that there are no leftovers and then install it again.

**Comment by Excal-rs** [comment]
> Hey all,
> 
> this issue might be due to the python upgrade. Try uninstall first all packages, make sure that there are no leftovers and then install it again.

by all packages do u mean all protonvpn packages?

**Comment by calexandru2018** [comment]
@Excal-rs yes that is correct.

**Comment by Excal-rs** [comment]
@calexandru2018 I have tried removing all packages and then installing but the error still occurs

**Comment by Excal-rs** [comment]
@calexandru2018 thank you, i uninstalled protonvpn and then updated everything using the `add/remove software` then installed  `protonvpn` and it has seemed to fix my issue.

**Comment by Graninius** [comment]
Removed all protonvpn related packages and then installed only protonvpn-gui (it'll install all needed depences). It fixed my issue.
Manjaro latest, unstabile

**Comment by Dawgora** [comment]
Yup, had the same issue that I couldn't start the protonvpn-gui/cli.
How I fixed this on my manjaro:
Kernel Release: 5.10.89-1-MANJARO
Python 3.10.1

1. `yay -Rs protonvpn` (removed everything related to protonvpn)
2. ` pacman -Qm | grep protonvpn` (checked if anything else was in there, if there was, I deleted it.)
3. `python -m pip list | grep proton` (checked if I had something inside my pip regarding proton, if I had I just `pip3 uninstall ____`)
4. `sudo rm -R ~/.cache/protonvpn` (cleared the cache) (also, if you want to, you can `sudo rm -rf ~/.config/protonvpn`)
5. Rebooted the sytstem
6. `pamac build protonvpn` (installed the protonvpn, with GUI and cli)

**Comment by Excal-rs** [comment]
@Dawgora 
> Yup, had the same issue that I couldn't start the protonvpn-gui/cli.
> How I fixed this on my manjaro:
> Kernel Release: 5.10.89-1-MANJARO
> Python 3.10.1
> 
> 1. `yay -Rs protonvpn` (removed everything related to protonvpn)
> 2. ` pacman -Qm | grep protonvpn` (checked if anything else was in there, if there was, I deleted it.)
> 3. `python -m pip list | grep proton` (checked if I had something inside my pip regarding proton, if I had I just `pip3 uninstall ____`)
> 4. `sudo rm -R ~/.cache/protonvpn` (cleared the cache) (also, if you want to, you can `sudo rm -rf ~/.config/protonvpn`)
> 5. Rebooted the sytstem
> 6. `pamac build protonvpn` (installed the protonvpn, with GUI and cli) 

thank you for your in depth explanation and step by step, as I just accidentally fixed it accidentally without knowing what was causing the issue

**Comment by Kameleon-07** [comment]
I have the issue with starting protonvpn too.
input: `$ protonvpn`
output:

`Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-gui==1.7.0', 'console_scripts', 'protonvpn')())
  File "/usr/bin/protonvpn", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration`

I installed it from aur using yay. I tried fixing it with solutions in this issue and someone else's but nothing, doesn't work.
My distro is Arch Linux.
Kernel: Linux 5.10.94-xanmod2-2-lts
Python version: 3.10.2

**Comment by pwltr** [comment]
I was able to fix this issue by updating the packages to use Python3.10.
If you're on Manjaro/Arch see explanation here:
https://forum.manjaro.org/t/stable-update-2022-01-02-kernels-systemd-kde-frameworks-mesa-xorg-server-wine-python-3-10/97104

Essentially it's this:

> You may need to rebuild any Python packages you’ve installed from the AUR. To get a list of them, you can run:
> `pacman -Qoq /usr/lib/python3.9`
> 
> And to rebuild them all at once with an AUR helper such as yay, you can do:
> 
> `yay -S $(pacman -Qoq /usr/lib/python3.9) --answerclean All`
> But if any of the packages don’t work with Python 3.10 yet, this might fail halfway through and you’ll have to do rebuild the remaining ones one or a few at a time.

Hope this helps
