### ISSUE TITLE
AttributeError: 'APISession' object has no attribute 'delinquent'

### ISSUE THREAD

**Issue by phrxmd** [ProtonVPN/linux-app#63]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [X] I have searched open and closed issues for duplicates
- [X] This isn't a feature request
- [X] This is not a report about my app not working as expected

----------------------------------------
I am currently compiling the GUI app for OpenSUSE. I'm doing this by adapting the provided .spec file. The app compiles fine; however when starting it, I get the following error message, and the window doesn't open:

    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/protonvpn_gui/main.py", line 265, in do_activate
        win = self.get_dashboard_window()
      File "/usr/lib/python3.8/site-packages/protonvpn_gui/main.py", line 295, in get_dashboard_window
        return DashboardView(application=self)
      File "/usr/lib/python3.8/site-packages/protonvpn_gui/view/dashboard.py", line 159, in __init__
        self.setup_properties()
      File "/usr/lib/python3.8/site-packages/protonvpn_gui/view/dashboard.py", line 313, in setup_properties
        self.quick_settings_popover = QuickSettingsPopoverView(
      File "/usr/lib/python3.8/site-packages/protonvpn_gui/view/quick_settings_popover.py", line 30, in __init__
        self.__create_widgets()
      File "/usr/lib/python3.8/site-packages/protonvpn_gui/view/quick_settings_popover.py", line 146, in __create_widgets
        self.__create_secure_core_buttons()
      File "/usr/lib/python3.8/site-packages/protonvpn_gui/view/quick_settings_popover.py", line 176, in __create_secure_core_buttons
        self.secure_core_button_on = SecureCoreOn(self)
      File "/usr/lib/python3.8/site-packages/protonvpn_gui/view/quick_settings_popover.py", line 439, in __init__
        if self.can_user_access_feature:
      File "/usr/lib/python3.8/site-packages/protonvpn_gui/view/quick_settings_popover.py", line 449, in can_user_access_feature
        return not self.delinquent and self.vpn_tier >= ServerTierEnum.PLUS_VISIONARY.value
      File "/usr/lib/python3.8/site-packages/protonvpn_gui/view/quick_settings_popover.py", line 294, in delinquent
        return protonvpn.get_session().delinquent
    AttributeError: 'APISession' object has no attribute 'delinquent'

I guess this comes form some package mismatch? My only modification so far has been to change the spec file to the OpenSUSE package names:

    BuildRequires: python38-devel
    BuildRequires: python38-setuptools
    BuildRequires: desktop-file-utils
    Requires: python38-protonvpn-nm-lib >= 3.4.0
    Requires: python38-gobject
    Requires: python38-psutil
    #Requires: gtk3
    Requires: libgtk-3-0
    #Requires: webkit2gtk3
    Requires: typelib-1_0-WebKit2-4_0
    Requires: libwebkit2gtk-4_0-37
    #Suggests: libappindicator-gtk3
    Suggests: libappindicator
    Suggests: gnome-tweaks
    #Suggests: gnome-shell-extension-appindicator

**Comment by calexandru2018** [comment]
Hey @phrxmd 

You need to use the latest version of the library, that’s why it isn’t working.

**Comment by phrxmd** [comment]
OK, that explains it. The `.spec` file calls for a library version >3.4.0, I have 3.6.0 installed (from Tumbleweed repositories) and thought it was OK, but the library is already at 3.7.0. I will try and recompile the library as well.

**Comment by phrxmd** [comment]
Got it working, thank you!
