### ISSUE TITLE
App fails to launch

### ISSUE THREAD

**Issue by heiserhorn** [ProtonVPN/linux-app#8]
Hi,

I am running debian (sid with some experimental packages). I recently updated some gnome related packages in the experimental repo. Since the update the app does not work anymore. I can connect via CLI.

When launching the app from the desktop icon the result is a window with almost no element in it. If I launch it from the terminal, the window does not even appear. Here the terminal output:

`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_gui/main.py", line 147, in do_activate
    win = self.get_dashboard_window()
  File "/usr/lib/python3/dist-packages/protonvpn_gui/main.py", line 179, in get_dashboard_window
    return DashboardView(
  File "/usr/lib/python3/dist-packages/protonvpn_gui/view/dashboard.py", line 157, in __init__
    self.quick_settings_popover = QuickSettingsPopoverView(
  File "/usr/lib/python3/dist-packages/protonvpn_gui/view/quick_settings_popover.py", line 32, in __init__
    self.__create_widgets()
  File "/usr/lib/python3/dist-packages/protonvpn_gui/view/quick_settings_popover.py", line 139, in __create_widgets
    self.__create_secure_core_buttons()
  File "/usr/lib/python3/dist-packages/protonvpn_gui/view/quick_settings_popover.py", line 168, in __create_secure_core_buttons
    self.secure_core_button_off = SecureCoreOff(self)
  File "/usr/lib/python3/dist-packages/protonvpn_gui/view/quick_settings_popover.py", line 379, in __init__
    super().__init__(
  File "/usr/lib/python3/dist-packages/protonvpn_gui/view/quick_settings_popover.py", line 247, in __init__
    self.__img = WidgetFactory.image(img_factory_name)
  File "/usr/lib/python3/dist-packages/protonvpn_gui/patterns/factory/abstract_widget_factory.py", line 38, in image
    return subclass.factory(widget, extra_arg)
  File "/usr/lib/python3/dist-packages/protonvpn_gui/patterns/factory/concrete_factory/image_factory.py", line 27, in factory
    return subclasses_dict[widget_name](extra_arg)
  File "/usr/lib/python3/dist-packages/protonvpn_gui/patterns/factory/concrete_factory/image_factory.py", line 563, in __init__
    self.create_icon_pixbuf_from_name(
  File "/usr/lib/python3/dist-packages/protonvpn_gui/patterns/factory/concrete_factory/image_factory.py", line 210, in create_icon_pixbuf_from_name
    return GdkPixbuf.Pixbuf.new_from_file_at_scale(
gi.repository.GLib.Error: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/usr/lib/python3/dist-packages/protonvpn_gui/assets/icons/secure-core.imageset/secure-core-off.svg” (3)
`

Thanks

Mike

**Comment by calexandru2018** [comment]
Hey @heiserhorn 

Based on your input (experimental packages) I would say that that could be the issue, as the problem arises at `Couldn’t recognize the image file format for file` for the `secure-core-off.svg` file, meaning that for some reason it can not read the `.svg`. You could check if the file is there to be sure, but that I currently my suspicion. What is your GTK version ?

**Comment by heiserhorn** [comment]
thanks @calexandru2018 

Version of libgtk-3 from experimental is 3.24.29-1 

I also found some broken dependencies and probably that's the cause.

I reverted to unstable packages and everything works a expected.

I suggest to close the issue until the new version of gnome and gtk reaches unstable after the freeze.

Cheers
