### ISSUE TITLE
fail to start a vpn connection

### ISSUE THREAD

**Issue by rafirafirafi** [ProtonVPN/linux-app#9]
debian 11
kde

when i start a connection i get a popup dialog asking to "provide the secrets for the VPN connection 'ProtonVPN US#43'

logs are 

INFO:protonvpn-gui:Connection was setup
INFO:protonvpn-gui:Displaying connection information
INFO:protonvpn-gui:Attempting to connect
INFO:protonvpn:Checking for internet connectivity
INFO:protonvpn:Skipping as killswitch is enabled
INFO:protonvpn:Starting VPN connection
INFO:protonvpn:Getting VPN from "NetworkManagerConnectionTypeEnum.ALL" connections
INFO:protonvpn:VPN connection: <NM.RemoteConnection object at 0x7fcbe08685c0 (NMRemoteConnection at 0x62df650)>
INFO:protonvpn:Starting VPN connection
INFO:protonvpn:Callback type: "start"
ERROR:protonvpn:Exception: NM.Client.activate_connection_finish() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py", line 117, in __dynamic_callback
    (callback_type_dict[callback_type]["finish_function"])(result)
TypeError: NM.Client.activate_connection_finish() takes exactly 2 arguments (1 given)
INFO:protonvpn:Template hash "aa91e34fef0f8a1a72a812a4b1845354222bdf5771881532805083eb7caab143"
INFO:protonvpn:Generated hash at runtime "aa91e34fef0f8a1a72a812a4b1845354222bdf5771881532805083eb7caab143"
INFO:protonvpn:Get connection interface from 'proton0' virtual device.
ERROR:protonvpn:org.freedesktop.NetworkManager.Settings.PermissionDenied: uid 1000 has no permission to perform this operation
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/dbus/dbus_wrapper.py", line 257, in get_vpn_interface
    all_settings = self.get_all_conn_settings(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/dbus/dbus_wrapper.py", line 391, in get_all_conn_settings
    return iface.GetSettings()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.NetworkManager.Settings.PermissionDenied: uid 1000 has no permission to perform this operation
INFO:protonvpn:Found virtual device 'proton0'.
INFO:protonvpn:ProtonVPN conn info: [True, dbus.UInt32(1, variant_level=1), dbus.ObjectPath('/org/freedesktop/NetworkManager/ActiveConnection/18')]
INFO:protonvpn:Adding listener to active ProtonVPN AU#43 connection at /org/freedesktop/NetworkManager/ActiveConnection/18

**Comment by calexandru2018** [comment]
Hey @rafirafirafi 

Is this still reproducible after the stable release ?

**Comment by Haggus** [comment]
I'd like to chip in and say I'm running into the same issue.

Manjaro Linux.
CLI version of protonvpn.

When connecting, I see:
`Setting up ProtonVPN.
Connecting to ProtonVPN on CH#8 with TCP.`
Then nothing. It never connects.

Here is part of the logs.

> 2021-06-28 21:51:14,408 — ipv6_leak_protection.py — INFO — __init__:45 — Intialized IPv6 leak protection manager
2021-06-28 21:51:14,410 — ipv6_leak_protection.py — INFO — get_status_connectivity_check:256 — Conn check available (1) - Conn check enabled (0)
2021-06-28 21:51:14,410 — nm_client.py — INFO — _pre_setup_connection:221 — Running pre-setup connection.
2021-06-28 21:51:14,410 — ipv6_leak_protection.py — INFO — manage:54 — Manage IPV6: KillSwitchActionEnum.ENABLE
2021-06-28 21:51:14,412 — ipv6_leak_protection.py — INFO — get_status_connectivity_check:256 — Conn check available (1) - Conn check enabled (0)
2021-06-28 21:51:14,434 — ipv6_leak_protection.py — INFO — update_connection_status:218 — IPv6 status: {'pvpn-ipv6leak-protection': {<KillSwitchInterfaceTrackerEnum.EXISTS: 0>: False, <KillSwitchInterfaceTrackerEnum.IS_RUNNING: 1>: False}}
2021-06-28 21:51:14,434 — ipv6_leak_protection.py — INFO — add_leak_protection:75 — Adding IPv6 leak protection
2021-06-28 21:51:14,435 — ipv6_leak_protection.py — INFO — manage:54 — Manage IPV6: KillSwitchActionEnum.DISABLE
2021-06-28 21:51:14,436 — ipv6_leak_protection.py — INFO — get_status_connectivity_check:256 — Conn check available (1) - Conn check enabled (0)
2021-06-28 21:51:14,458 — ipv6_leak_protection.py — INFO — update_connection_status:218 — IPv6 status: {'pvpn-ipv6leak-protection': {<KillSwitchInterfaceTrackerEnum.EXISTS: 0>: False, <KillSwitchInterfaceTrackerEnum.IS_RUNNING: 1>: False}}
2021-06-28 21:51:14,458 — ipv6_leak_protection.py — INFO — remove_leak_protection:108 — Removing IPv6 leak protection
2021-06-28 21:51:14,510 — nm_client_mixin.py — INFO — __dynamic_callback:90 — Callback type: "add"
2021-06-28 21:51:14,510 — nm_client_mixin.py — ERROR — __dynamic_callback:124 — Exception: NM.Client.add_connection_finish() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py", line 117, in __dynamic_callback
    (callback_type_dict[callback_type]["finish_function"])(result)
TypeError: NM.Client.add_connection_finish() takes exactly 2 arguments (1 given)
2021-06-28 21:51:14,511 — utilities.py — INFO — ensure_internet_connection_is_available:21 — Checking for internet connectivity
2021-06-28 21:51:14,511 — utilities.py — INFO — ensure_internet_connection_is_available:23 — Skipping as killswitch is enabled
2021-06-28 21:51:14,511 — nm_client.py — INFO — connect:89 — Starting VPN connection
2021-06-28 21:51:14,511 — nm_client.py — INFO — __get_protonvpn_connection:172 — Getting VPN from "NetworkManagerConnectionTypeEnum.ALL" connections
2021-06-28 21:51:14,511 — nm_client.py — INFO — __get_protonvpn_connection:207 — VPN connection: <NM.RemoteConnection object at 0x7ff5f3d6c180 (NMRemoteConnection at 0x56117268df10)>
2021-06-28 21:51:14,512 — nm_client_mixin.py — INFO — _start_connection_async:29 — Starting VPN connection
2021-06-28 21:51:14,545 — nm_client_mixin.py — INFO — __dynamic_callback:90 — Callback type: "start"
2021-06-28 21:51:14,546 — nm_client_mixin.py — ERROR — __dynamic_callback:124 — Exception: NM.Client.activate_connection_finish() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py", line 117, in __dynamic_callback
    (callback_type_dict[callback_type]["finish_function"])(result)
TypeError: NM.Client.activate_connection_finish() takes exactly 2 arguments (1 given)

I'm happy to provide additional info to help solve this issue :)

**Comment by calexandru2018** [comment]
Hey @Haggus 

I think checking the NM logs should help. After connecting (and while waiting for confirmation from CLI) type in another console `journalctl -eu NetworkManager`

**Comment by Haggus** [comment]
Here is what I'm getting from NetworkManager:
```Jul 08 08:28:59 wonderland NetworkManager[733]: <info>  [1625725739.1907] manager: startup complete
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3267] manager: (ipv6leakintrf0): new Dummy device (/org/freedesktop/NetworkManager/Devices/3)
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3289] device (ipv6leakintrf0): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3295] audit: op="connection-add" uuid="c498b4a7-0bca-4e25-aa97-d2750cd8ef94" name="pvpn-ipv6leak-protection" pid=2525 uid=1000 result="success"
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3306] device (ipv6leakintrf0): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'managed')
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3308] policy: auto-activating connection 'pvpn-ipv6leak-protection' (c498b4a7-0bca-4e25-aa97-d2750cd8ef94)
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3309] device (ipv6leakintrf0): Activation: starting connection 'pvpn-ipv6leak-protection' (c498b4a7-0bca-4e25-aa97-d2750cd8ef94)
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3310] device (ipv6leakintrf0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'managed')
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3311] device (ipv6leakintrf0): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3312] device (ipv6leakintrf0): state change: config -> ip-config (reason 'none', sys-iface-state: 'managed')
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3313] dhcp4 (ipv6leakintrf0): activation: beginning transaction (timeout in 45 seconds)
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3317] device (ipv6leakintrf0): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'managed')
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3341] audit: op="connection-add" uuid="4b0eb9c7-0667-40fb-ba7a-5fb761925537" name="ProtonVPN HU#4" pid=2410 uid=1000 result="success"
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3361] device (ipv6leakintrf0): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'managed')
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3362] device (ipv6leakintrf0): state change: secondaries -> activated (reason 'none', sys-iface-state: 'managed')
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3366] policy: set 'pvpn-ipv6leak-protection' (ipv6leakintrf0) as default for IPv6 routing and DNS
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3428] device (ipv6leakintrf0): Activation: successful, device activated.
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3498] audit: op="connection-activate" uuid="4b0eb9c7-0667-40fb-ba7a-5fb761925537" name="ProtonVPN HU#4" pid=2410 uid=1000 result="success"
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3519] vpn-connection[0x5604e79ea130,4b0eb9c7-0667-40fb-ba7a-5fb761925537,"ProtonVPN HU#4",0]: Started the VPN service, PID 2538
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3598] vpn-connection[0x5604e79ea130,4b0eb9c7-0667-40fb-ba7a-5fb761925537,"ProtonVPN HU#4",0]: Saw the service appear; activating connection
Jul 08 08:31:29 wonderland NetworkManager[733]: <error> [1625725889.3623] vpn-connection[0x5604e79ea130,4b0eb9c7-0667-40fb-ba7a-5fb761925537,"ProtonVPN HU#4",0]: Failed to request VPN secrets #3: No agents were available for this request.
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3630] vpn-connection[0x5604e79ea130,4b0eb9c7-0667-40fb-ba7a-5fb761925537,"ProtonVPN HU#4",0]: VPN plugin: state changed: stopped (6)
Jul 08 08:31:29 wonderland NetworkManager[733]: <info>  [1625725889.3636] vpn-connection[0x5604e79ea130,4b0eb9c7-0667-40fb-ba7a-5fb761925537,"ProtonVPN HU#4",0]: VPN service disappeared
```
I notice it says "no agents were available" and I'm assuming it's talking about either gnome-keyring or Kwallet. Here is the output of `ps -aux | grep gnome`
```
alice       1272  0.0  0.0 310416  7160 ?        Sl   08:30   0:00 /usr/bin/gnome-keyring-daemon --daemonize --login
```

**Comment by calexandru2018** [comment]
@Haggus please check this one #12

**Comment by Haggus** [comment]
@calexandru2018 It worked! Didn't suspect nm-applet must be running in order to connect. Thanks for the help :)

**Comment by calexandru2018** [comment]
@rafirafirafi could you also please confirm ? In absence of an answer this ticket might risk being closed.

**Comment by rafirafirafi** [comment]
it works perfectly now! thank you

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ediowar** [comment]
Is the connection established on the second try?
