### ISSUE TITLE
Is the installation guide in Arch/Manjaro correct?

### ISSUE THREAD

**Issue by renaldofreire** [ProtonVPN/linux-app#91]
I rigidly followed [this](https://protonvpn.com/support/official-linux-client-arch/) tutorial to install protonvpn on Arch Linux. 

But I can't use it. The following problems occur:

1. After trying to connect to a vpn, the application loads infinitely;
2. The terminal version doesn't work either. 

**After forcing a user logout, this error appeared:**

```
org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/5”
```

**Here is the log collected directly via the terminal**
```
➜  ~ protonvpn
(protonvpn:20050): Gdk-CRITICAL **: 02:43:24.504: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py:11: Warning: g_main_context_push_thread_default: assertion 'acquired_context' failed
  nm_client = NM.Client.new(None)
/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py:11: Warning: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed
  nm_client = NM.Client.new(None)

/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py:52: Warning: g_main_context_push_thread_default: assertion 'acquired_context' failed
  connection.delete_async(
/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py:52: Warning: g_main_context_pop_thread_default: assertion 'stack != NULL' failed
  connection.delete_async(
^CTraceback (most recent call last):
  File "/usr/bin/protonvpn", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-gui==1.11.0', 'console_scripts', 'protonvpn')())
  File "/usr/lib/python3.10/site-packages/protonvpn_gui/main.py", line 322, in main
    exit_status = app.run(sys.argv)
  File "/usr/lib/python3.10/site-packages/gi/overrides/Gio.py", line 40, in run
    with register_sigint_fallback(self.quit):
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/lib/python3.10/site-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt
^C
```

**Here are some screenshots**

![Alt text](https://i.imgur.com/PD9Icex.png "a title")
![Alt text](https://i.imgur.com/oXDPFDh.png "a title")

**Comment by mike-lloyd03** [comment]
I cannot connect on Arch either with the GUI or the CLI. It attempts to connect indefinitely but never finishes.

**Comment by guigirl42** [comment]
Hello 

_[disclaimer: i'm just another User like you both, i'm not from Proton]._

It works _really well_ for me in my Tower's **Arch KDE**, & _reasonably_ ok also in my Lappy's Mint Cinnamon [wherein it manifests a lousy internet-blockage post-Resume if i do not remember to _Disconnect_ it before Suspend -- a glitch entirely NOT present in my Arch KDE]. 

As you just read, my DE is KDE. Are you using a different DE/WM? I'm wondering if possibly your DE/WM equivalent of Kwallet might not be unlocking the app for you?

Otoh, maybe one or other of you might have succumbed to the same problem that had been plaguing my Lappy's Mint Cinnamon for several nights, which i finally "solved" today after hours more research & testing ... the culprit being the app's  inbuilt IPv6 leak-blocker [https://github.com/ProtonVPN/linux-app/issues/20]. I discovered that [despite being n/a for my Arch], i had to disconnect the connection on Lappy before rebooting or suspending, otherwise next time around i had no connection, & when that annoyance happened, i had to recover by manually deactivating the killswitch [even if i'd not actually been using it] via `protonvpn-cli ks --off` [https://protonvpn.com/support/what-is-kill-switch/]. 

Fwiw.

**Comment by Soliprem** [comment]
have you managed any progress on this?
